/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.contract;

import com.mercoa.api.core.ClientOptions;
import com.mercoa.api.core.RequestOptions;
import com.mercoa.api.resources.contract.requests.ApplyContractFeedbackRequest;
import com.mercoa.api.resources.contract.requests.ApplyInvoiceFeedbackRequest;
import com.mercoa.api.resources.contract.requests.FindContractRequest;
import com.mercoa.api.resources.contract.requests.PreviewContractInvoicesRequest;
import com.mercoa.api.resources.contracttypes.types.ContractCreateRequest;
import com.mercoa.api.resources.contracttypes.types.ContractResponse;
import com.mercoa.api.resources.contracttypes.types.ContractUpdateRequest;
import com.mercoa.api.resources.contracttypes.types.FindContractResponse;
import com.mercoa.api.resources.contracttypes.types.GenerateContractAsyncJobResponse;
import com.mercoa.api.resources.contracttypes.types.GenerateContractAsyncResponse;
import com.mercoa.api.resources.contracttypes.types.GenerateContractRequest;
import com.mercoa.api.resources.contracttypes.types.GenerateContractResponse;
import com.mercoa.api.resources.invoicetypes.types.InvoiceResponse;
import java.util.List;

public class ContractClient {
    protected final ClientOptions clientOptions;

    private final RawContractClient rawClient;

    public ContractClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawContractClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawContractClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Generate a new contract object from a Base64 encoded PDF of a contract. This endpoint will block until the contract is generated.
     */
    public GenerateContractResponse generateContract(GenerateContractRequest request) {
        return this.rawClient.generateContract(request).body();
    }

    /**
     * Generate a new contract object from a Base64 encoded PDF of a contract. This endpoint will block until the contract is generated.
     */
    public GenerateContractResponse generateContract(GenerateContractRequest request, RequestOptions requestOptions) {
        return this.rawClient.generateContract(request, requestOptions).body();
    }

    /**
     * Generate a new contract object from a Base64 encoded PDF of a contract. This endpoint will return immediately and the contract will be generated asynchronously.
     */
    public GenerateContractAsyncResponse generateContractRunAsync(GenerateContractRequest request) {
        return this.rawClient.generateContractRunAsync(request).body();
    }

    /**
     * Generate a new contract object from a Base64 encoded PDF of a contract. This endpoint will return immediately and the contract will be generated asynchronously.
     */
    public GenerateContractAsyncResponse generateContractRunAsync(
            GenerateContractRequest request, RequestOptions requestOptions) {
        return this.rawClient.generateContractRunAsync(request, requestOptions).body();
    }

    /**
     * Get the status and results of an asynchronous contract generation job.
     */
    public GenerateContractAsyncJobResponse generateContractGetAsync(String jobId) {
        return this.rawClient.generateContractGetAsync(jobId).body();
    }

    /**
     * Get the status and results of an asynchronous contract generation job.
     */
    public GenerateContractAsyncJobResponse generateContractGetAsync(String jobId, RequestOptions requestOptions) {
        return this.rawClient.generateContractGetAsync(jobId, requestOptions).body();
    }

    /**
     * Generate previews of the invoices that will be created from the provided contract.
     */
    public List<InvoiceResponse> previewInvoices(PreviewContractInvoicesRequest request) {
        return this.rawClient.previewInvoices(request).body();
    }

    /**
     * Generate previews of the invoices that will be created from the provided contract.
     */
    public List<InvoiceResponse> previewInvoices(
            PreviewContractInvoicesRequest request, RequestOptions requestOptions) {
        return this.rawClient.previewInvoices(request, requestOptions).body();
    }

    /**
     * Apply feedback to a contract, generating an updated contract object.  NOTE: This works by re-extracting the contract details with the provided feedback in mind.
     */
    public ContractResponse applyContractFeedback(String contractId, ApplyContractFeedbackRequest request) {
        return this.rawClient.applyContractFeedback(contractId, request).body();
    }

    /**
     * Apply feedback to a contract, generating an updated contract object.  NOTE: This works by re-extracting the contract details with the provided feedback in mind.
     */
    public ContractResponse applyContractFeedback(
            String contractId, ApplyContractFeedbackRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .applyContractFeedback(contractId, request, requestOptions)
                .body();
    }

    /**
     * Apply feedback to an invoice, generating an updated invoice object.
     */
    public InvoiceResponse applyInvoiceFeedback(String contractId, ApplyInvoiceFeedbackRequest request) {
        return this.rawClient.applyInvoiceFeedback(contractId, request).body();
    }

    /**
     * Apply feedback to an invoice, generating an updated invoice object.
     */
    public InvoiceResponse applyInvoiceFeedback(
            String contractId, ApplyInvoiceFeedbackRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .applyInvoiceFeedback(contractId, request, requestOptions)
                .body();
    }

    /**
     * Search contracts for all entities in the organization
     */
    public FindContractResponse find() {
        return this.rawClient.find().body();
    }

    /**
     * Search contracts for all entities in the organization
     */
    public FindContractResponse find(FindContractRequest request) {
        return this.rawClient.find(request).body();
    }

    /**
     * Search contracts for all entities in the organization
     */
    public FindContractResponse find(FindContractRequest request, RequestOptions requestOptions) {
        return this.rawClient.find(request, requestOptions).body();
    }

    public ContractResponse create(ContractCreateRequest request) {
        return this.rawClient.create(request).body();
    }

    public ContractResponse create(ContractCreateRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    public ContractResponse get(String contractId) {
        return this.rawClient.get(contractId).body();
    }

    public ContractResponse get(String contractId, RequestOptions requestOptions) {
        return this.rawClient.get(contractId, requestOptions).body();
    }

    public ContractResponse update(String contractId) {
        return this.rawClient.update(contractId).body();
    }

    public ContractResponse update(String contractId, ContractUpdateRequest request) {
        return this.rawClient.update(contractId, request).body();
    }

    public ContractResponse update(String contractId, ContractUpdateRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(contractId, request, requestOptions).body();
    }

    public void delete(String contractId) {
        this.rawClient.delete(contractId).body();
    }

    public void delete(String contractId, RequestOptions requestOptions) {
        this.rawClient.delete(contractId, requestOptions).body();
    }
}
