/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.invoice.collection;

import com.mercoa.api.core.ClientOptions;
import com.mercoa.api.core.RequestOptions;
import com.mercoa.api.resources.collectiontypes.types.ActionResponse;
import com.mercoa.api.resources.collectiontypes.types.UpdateNextActionRequest;
import java.util.Optional;

public class CollectionClient {
    protected final ClientOptions clientOptions;

    private final RawCollectionClient rawClient;

    public CollectionClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawCollectionClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawCollectionClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Get the collection agent's next action on this invoice. This endpoint will return an empty object if there is no action to return.
     */
    public Optional<ActionResponse> getNextAction(String invoiceId) {
        return this.rawClient.getNextAction(invoiceId).body();
    }

    /**
     * Get the collection agent's next action on this invoice. This endpoint will return an empty object if there is no action to return.
     */
    public Optional<ActionResponse> getNextAction(String invoiceId, RequestOptions requestOptions) {
        return this.rawClient.getNextAction(invoiceId, requestOptions).body();
    }

    /**
     * Update the collection agent's next action on this invoice with natural language. Note that updating any APPROVED action will reset the action to SUGGESTED.  This endpoint will throw an error if there is no action to update.
     */
    public ActionResponse updateNextAction(String invoiceId, UpdateNextActionRequest request) {
        return this.rawClient.updateNextAction(invoiceId, request).body();
    }

    /**
     * Update the collection agent's next action on this invoice with natural language. Note that updating any APPROVED action will reset the action to SUGGESTED.  This endpoint will throw an error if there is no action to update.
     */
    public ActionResponse updateNextAction(
            String invoiceId, UpdateNextActionRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .updateNextAction(invoiceId, request, requestOptions)
                .body();
    }

    /**
     * Approve the collection agent's next action on this invoice. This endpoint will throw an error if there is no action to approve.
     */
    public ActionResponse approveNextAction(String invoiceId) {
        return this.rawClient.approveNextAction(invoiceId).body();
    }

    /**
     * Approve the collection agent's next action on this invoice. This endpoint will throw an error if there is no action to approve.
     */
    public ActionResponse approveNextAction(String invoiceId, RequestOptions requestOptions) {
        return this.rawClient.approveNextAction(invoiceId, requestOptions).body();
    }
}
