/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.webhooks.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mercoa.api.core.ObjectMappers;
import com.mercoa.api.resources.collectiontypes.types.EmailMessageResponse;
import com.mercoa.api.resources.invoicetypes.types.InvoiceResponse;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InvoiceCollectionEventWebhook.Builder.class)
public final class InvoiceCollectionEventWebhook {
    private final String eventType;

    private final InvoiceResponse invoice;

    private final Optional<EmailMessageResponse> email;

    private final Map<String, Object> additionalProperties;

    private InvoiceCollectionEventWebhook(
            String eventType,
            InvoiceResponse invoice,
            Optional<EmailMessageResponse> email,
            Map<String, Object> additionalProperties) {
        this.eventType = eventType;
        this.invoice = invoice;
        this.email = email;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The type of the event.
     */
    @JsonProperty("eventType")
    public String getEventType() {
        return eventType;
    }

    /**
     * @return The invoice involved in the event.
     */
    @JsonProperty("invoice")
    public InvoiceResponse getInvoice() {
        return invoice;
    }

    /**
     * @return Email message related to the invoice collection.
     */
    @JsonProperty("email")
    public Optional<EmailMessageResponse> getEmail() {
        return email;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof InvoiceCollectionEventWebhook && equalTo((InvoiceCollectionEventWebhook) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(InvoiceCollectionEventWebhook other) {
        return eventType.equals(other.eventType) && invoice.equals(other.invoice) && email.equals(other.email);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.eventType, this.invoice, this.email);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EventTypeStage builder() {
        return new Builder();
    }

    public interface EventTypeStage {
        InvoiceStage eventType(@NotNull String eventType);

        Builder from(InvoiceCollectionEventWebhook other);
    }

    public interface InvoiceStage {
        _FinalStage invoice(@NotNull InvoiceResponse invoice);
    }

    public interface _FinalStage {
        InvoiceCollectionEventWebhook build();

        _FinalStage email(Optional<EmailMessageResponse> email);

        _FinalStage email(EmailMessageResponse email);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EventTypeStage, InvoiceStage, _FinalStage {
        private String eventType;

        private InvoiceResponse invoice;

        private Optional<EmailMessageResponse> email = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(InvoiceCollectionEventWebhook other) {
            eventType(other.getEventType());
            invoice(other.getInvoice());
            email(other.getEmail());
            return this;
        }

        /**
         * <p>The type of the event.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("eventType")
        public InvoiceStage eventType(@NotNull String eventType) {
            this.eventType = Objects.requireNonNull(eventType, "eventType must not be null");
            return this;
        }

        /**
         * <p>The invoice involved in the event.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("invoice")
        public _FinalStage invoice(@NotNull InvoiceResponse invoice) {
            this.invoice = Objects.requireNonNull(invoice, "invoice must not be null");
            return this;
        }

        /**
         * <p>Email message related to the invoice collection.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage email(EmailMessageResponse email) {
            this.email = Optional.ofNullable(email);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "email", nulls = Nulls.SKIP)
        public _FinalStage email(Optional<EmailMessageResponse> email) {
            this.email = email;
            return this;
        }

        @java.lang.Override
        public InvoiceCollectionEventWebhook build() {
            return new InvoiceCollectionEventWebhook(eventType, invoice, email, additionalProperties);
        }
    }
}
