/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.invoicetypes.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mercoa.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BulkInvoiceUpdateRequest.Builder.class)
public final class BulkInvoiceUpdateRequest {
    private final List<InvoiceUpdateRequestWithId> invoices;

    private final Map<String, Object> additionalProperties;

    private BulkInvoiceUpdateRequest(
            List<InvoiceUpdateRequestWithId> invoices, Map<String, Object> additionalProperties) {
        this.invoices = invoices;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("invoices")
    public List<InvoiceUpdateRequestWithId> getInvoices() {
        return invoices;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BulkInvoiceUpdateRequest && equalTo((BulkInvoiceUpdateRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BulkInvoiceUpdateRequest other) {
        return invoices.equals(other.invoices);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.invoices);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<InvoiceUpdateRequestWithId> invoices = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(BulkInvoiceUpdateRequest other) {
            invoices(other.getInvoices());
            return this;
        }

        @JsonSetter(value = "invoices", nulls = Nulls.SKIP)
        public Builder invoices(List<InvoiceUpdateRequestWithId> invoices) {
            this.invoices.clear();
            this.invoices.addAll(invoices);
            return this;
        }

        public Builder addInvoices(InvoiceUpdateRequestWithId invoices) {
            this.invoices.add(invoices);
            return this;
        }

        public Builder addAllInvoices(List<InvoiceUpdateRequestWithId> invoices) {
            if (invoices != null) {
                this.invoices.addAll(invoices);
            }
            return this;
        }

        public BulkInvoiceUpdateRequest build() {
            return new BulkInvoiceUpdateRequest(invoices, additionalProperties);
        }
    }
}
