/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.invoicetypes.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mercoa.api.core.ObjectMappers;
import com.mercoa.api.resources.paymentmethodtypes.types.CurrencyCode;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InvoiceMetricsPerDateResponse.Builder.class)
public final class InvoiceMetricsPerDateResponse {
    private final Optional<List<Map<String, String>>> group;

    private final OffsetDateTime date;

    private final double totalAmount;

    private final int totalCount;

    private final double averageAmount;

    private final CurrencyCode currency;

    private final Map<String, Object> additionalProperties;

    private InvoiceMetricsPerDateResponse(
            Optional<List<Map<String, String>>> group,
            OffsetDateTime date,
            double totalAmount,
            int totalCount,
            double averageAmount,
            CurrencyCode currency,
            Map<String, Object> additionalProperties) {
        this.group = group;
        this.date = date;
        this.totalAmount = totalAmount;
        this.totalCount = totalCount;
        this.averageAmount = averageAmount;
        this.currency = currency;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return If groupBy is provided, this will be the group by value.
     */
    @JsonProperty("group")
    public Optional<List<Map<String, String>>> getGroup() {
        return group;
    }

    @JsonProperty("date")
    public OffsetDateTime getDate() {
        return date;
    }

    @JsonProperty("totalAmount")
    public double getTotalAmount() {
        return totalAmount;
    }

    @JsonProperty("totalCount")
    public int getTotalCount() {
        return totalCount;
    }

    @JsonProperty("averageAmount")
    public double getAverageAmount() {
        return averageAmount;
    }

    @JsonProperty("currency")
    public CurrencyCode getCurrency() {
        return currency;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof InvoiceMetricsPerDateResponse && equalTo((InvoiceMetricsPerDateResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(InvoiceMetricsPerDateResponse other) {
        return group.equals(other.group)
                && date.equals(other.date)
                && totalAmount == other.totalAmount
                && totalCount == other.totalCount
                && averageAmount == other.averageAmount
                && currency.equals(other.currency);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.group, this.date, this.totalAmount, this.totalCount, this.averageAmount, this.currency);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DateStage builder() {
        return new Builder();
    }

    public interface DateStage {
        TotalAmountStage date(@NotNull OffsetDateTime date);

        Builder from(InvoiceMetricsPerDateResponse other);
    }

    public interface TotalAmountStage {
        TotalCountStage totalAmount(double totalAmount);
    }

    public interface TotalCountStage {
        AverageAmountStage totalCount(int totalCount);
    }

    public interface AverageAmountStage {
        CurrencyStage averageAmount(double averageAmount);
    }

    public interface CurrencyStage {
        _FinalStage currency(@NotNull CurrencyCode currency);
    }

    public interface _FinalStage {
        InvoiceMetricsPerDateResponse build();

        _FinalStage group(Optional<List<Map<String, String>>> group);

        _FinalStage group(List<Map<String, String>> group);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements DateStage, TotalAmountStage, TotalCountStage, AverageAmountStage, CurrencyStage, _FinalStage {
        private OffsetDateTime date;

        private double totalAmount;

        private int totalCount;

        private double averageAmount;

        private CurrencyCode currency;

        private Optional<List<Map<String, String>>> group = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(InvoiceMetricsPerDateResponse other) {
            group(other.getGroup());
            date(other.getDate());
            totalAmount(other.getTotalAmount());
            totalCount(other.getTotalCount());
            averageAmount(other.getAverageAmount());
            currency(other.getCurrency());
            return this;
        }

        @java.lang.Override
        @JsonSetter("date")
        public TotalAmountStage date(@NotNull OffsetDateTime date) {
            this.date = Objects.requireNonNull(date, "date must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("totalAmount")
        public TotalCountStage totalAmount(double totalAmount) {
            this.totalAmount = totalAmount;
            return this;
        }

        @java.lang.Override
        @JsonSetter("totalCount")
        public AverageAmountStage totalCount(int totalCount) {
            this.totalCount = totalCount;
            return this;
        }

        @java.lang.Override
        @JsonSetter("averageAmount")
        public CurrencyStage averageAmount(double averageAmount) {
            this.averageAmount = averageAmount;
            return this;
        }

        @java.lang.Override
        @JsonSetter("currency")
        public _FinalStage currency(@NotNull CurrencyCode currency) {
            this.currency = Objects.requireNonNull(currency, "currency must not be null");
            return this;
        }

        /**
         * <p>If groupBy is provided, this will be the group by value.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage group(List<Map<String, String>> group) {
            this.group = Optional.ofNullable(group);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "group", nulls = Nulls.SKIP)
        public _FinalStage group(Optional<List<Map<String, String>>> group) {
            this.group = group;
            return this;
        }

        @java.lang.Override
        public InvoiceMetricsPerDateResponse build() {
            return new InvoiceMetricsPerDateResponse(
                    group, date, totalAmount, totalCount, averageAmount, currency, additionalProperties);
        }
    }
}
