/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.invoice.approval;

import com.mercoa.api.core.ClientOptions;
import com.mercoa.api.core.RequestOptions;
import com.mercoa.api.resources.invoicetypes.types.AddApproverRequest;
import com.mercoa.api.resources.invoicetypes.types.ApprovalRequest;

public class ApprovalClient {
    protected final ClientOptions clientOptions;

    private final RawApprovalClient rawClient;

    public ApprovalClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawApprovalClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawApprovalClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Adds an approver to the invoice. Will select the first available approver slot that is not already filled and assign the approver to it. If no approver slots are available, an error will be returned. An explicit approver slot can be specified by setting the <code>approverSlot</code> field.
     */
    public void addApprover(String invoiceId, AddApproverRequest request) {
        this.rawClient.addApprover(invoiceId, request).body();
    }

    /**
     * Adds an approver to the invoice. Will select the first available approver slot that is not already filled and assign the approver to it. If no approver slots are available, an error will be returned. An explicit approver slot can be specified by setting the <code>approverSlot</code> field.
     */
    public void addApprover(String invoiceId, AddApproverRequest request, RequestOptions requestOptions) {
        this.rawClient.addApprover(invoiceId, request, requestOptions).body();
    }

    public void approve(String invoiceId, ApprovalRequest request) {
        this.rawClient.approve(invoiceId, request).body();
    }

    public void approve(String invoiceId, ApprovalRequest request, RequestOptions requestOptions) {
        this.rawClient.approve(invoiceId, request, requestOptions).body();
    }

    public void reject(String invoiceId, ApprovalRequest request) {
        this.rawClient.reject(invoiceId, request).body();
    }

    public void reject(String invoiceId, ApprovalRequest request, RequestOptions requestOptions) {
        this.rawClient.reject(invoiceId, request, requestOptions).body();
    }
}
