/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.invoice.bnpl;

import com.mercoa.api.core.ClientOptions;
import com.mercoa.api.core.RequestOptions;
import com.mercoa.api.resources.invoicetypes.types.BnplLoanResponse;
import com.mercoa.api.resources.invoicetypes.types.BnplOfferRequest;
import com.mercoa.api.resources.invoicetypes.types.BnplOfferResponse;

public class BnplClient {
    protected final ClientOptions clientOptions;

    private final RawBnplClient rawClient;

    public BnplClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawBnplClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawBnplClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Get a BNPL offer for an invoice
     */
    public BnplOfferResponse offer(String invoiceId, BnplOfferRequest request) {
        return this.rawClient.offer(invoiceId, request).body();
    }

    /**
     * Get a BNPL offer for an invoice
     */
    public BnplOfferResponse offer(String invoiceId, BnplOfferRequest request, RequestOptions requestOptions) {
        return this.rawClient.offer(invoiceId, request, requestOptions).body();
    }

    /**
     * Get information about a specific BNPL loan by loan ID
     */
    public BnplLoanResponse loan(String loanId) {
        return this.rawClient.loan(loanId).body();
    }

    /**
     * Get information about a specific BNPL loan by loan ID
     */
    public BnplLoanResponse loan(String loanId, RequestOptions requestOptions) {
        return this.rawClient.loan(loanId, requestOptions).body();
    }
}
