/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.organizationtypes.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mercoa.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GlobalNotificationConfigurationRequest.Builder.class)
public final class GlobalNotificationConfigurationRequest {
    private final Optional<InvoiceNotificationConfigurationRequest> invoice;

    private final Map<String, Object> additionalProperties;

    private GlobalNotificationConfigurationRequest(
            Optional<InvoiceNotificationConfigurationRequest> invoice, Map<String, Object> additionalProperties) {
        this.invoice = invoice;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("invoice")
    public Optional<InvoiceNotificationConfigurationRequest> getInvoice() {
        return invoice;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GlobalNotificationConfigurationRequest
                && equalTo((GlobalNotificationConfigurationRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GlobalNotificationConfigurationRequest other) {
        return invoice.equals(other.invoice);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.invoice);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<InvoiceNotificationConfigurationRequest> invoice = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GlobalNotificationConfigurationRequest other) {
            invoice(other.getInvoice());
            return this;
        }

        @JsonSetter(value = "invoice", nulls = Nulls.SKIP)
        public Builder invoice(Optional<InvoiceNotificationConfigurationRequest> invoice) {
            this.invoice = invoice;
            return this;
        }

        public Builder invoice(InvoiceNotificationConfigurationRequest invoice) {
            this.invoice = Optional.ofNullable(invoice);
            return this;
        }

        public GlobalNotificationConfigurationRequest build() {
            return new GlobalNotificationConfigurationRequest(invoice, additionalProperties);
        }
    }
}
