/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.organizationtypes.types;

import java.util.Optional;

public interface IGenericPaymentRailRequest {
    Optional<String> getName();

    boolean getActive();
}
