/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.customizationtypes.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mercoa.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FlatFee.Builder.class)
public final class FlatFee {
    private final double amount;

    private final Map<String, Object> additionalProperties;

    private FlatFee(double amount, Map<String, Object> additionalProperties) {
        this.amount = amount;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The flat amount that will be charged as a fee. For example, if the fee is $2.50, set this to 2.5.
     */
    @JsonProperty("amount")
    public double getAmount() {
        return amount;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FlatFee && equalTo((FlatFee) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FlatFee other) {
        return amount == other.amount;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.amount);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AmountStage builder() {
        return new Builder();
    }

    public interface AmountStage {
        _FinalStage amount(double amount);

        Builder from(FlatFee other);
    }

    public interface _FinalStage {
        FlatFee build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AmountStage, _FinalStage {
        private double amount;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(FlatFee other) {
            amount(other.getAmount());
            return this;
        }

        /**
         * <p>The flat amount that will be charged as a fee. For example, if the fee is $2.50, set this to 2.5.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("amount")
        public _FinalStage amount(double amount) {
            this.amount = amount;
            return this;
        }

        @java.lang.Override
        public FlatFee build() {
            return new FlatFee(amount, additionalProperties);
        }
    }
}
