/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.moov.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mercoa.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MoovWebhookBase.Builder.class)
public final class MoovWebhookBase implements IMoovWebhookBase {
    private final String eventId;

    private final String type;

    private final String createdOn;

    private final Map<String, Object> additionalProperties;

    private MoovWebhookBase(String eventId, String type, String createdOn, Map<String, Object> additionalProperties) {
        this.eventId = eventId;
        this.type = type;
        this.createdOn = createdOn;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The Moov event ID
     */
    @JsonProperty("eventID")
    @java.lang.Override
    public String getEventId() {
        return eventId;
    }

    /**
     * @return The Moov event type
     */
    @JsonProperty("type")
    @java.lang.Override
    public String getType() {
        return type;
    }

    /**
     * @return The Moov event creation date
     */
    @JsonProperty("createdOn")
    @java.lang.Override
    public String getCreatedOn() {
        return createdOn;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MoovWebhookBase && equalTo((MoovWebhookBase) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MoovWebhookBase other) {
        return eventId.equals(other.eventId) && type.equals(other.type) && createdOn.equals(other.createdOn);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.eventId, this.type, this.createdOn);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EventIdStage builder() {
        return new Builder();
    }

    public interface EventIdStage {
        /**
         * <p>The Moov event ID</p>
         */
        TypeStage eventId(@NotNull String eventId);

        Builder from(MoovWebhookBase other);
    }

    public interface TypeStage {
        /**
         * <p>The Moov event type</p>
         */
        CreatedOnStage type(@NotNull String type);
    }

    public interface CreatedOnStage {
        /**
         * <p>The Moov event creation date</p>
         */
        _FinalStage createdOn(@NotNull String createdOn);
    }

    public interface _FinalStage {
        MoovWebhookBase build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EventIdStage, TypeStage, CreatedOnStage, _FinalStage {
        private String eventId;

        private String type;

        private String createdOn;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MoovWebhookBase other) {
            eventId(other.getEventId());
            type(other.getType());
            createdOn(other.getCreatedOn());
            return this;
        }

        /**
         * <p>The Moov event ID</p>
         * <p>The Moov event ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("eventID")
        public TypeStage eventId(@NotNull String eventId) {
            this.eventId = Objects.requireNonNull(eventId, "eventId must not be null");
            return this;
        }

        /**
         * <p>The Moov event type</p>
         * <p>The Moov event type</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public CreatedOnStage type(@NotNull String type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>The Moov event creation date</p>
         * <p>The Moov event creation date</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("createdOn")
        public _FinalStage createdOn(@NotNull String createdOn) {
            this.createdOn = Objects.requireNonNull(createdOn, "createdOn must not be null");
            return this;
        }

        @java.lang.Override
        public MoovWebhookBase build() {
            return new MoovWebhookBase(eventId, type, createdOn, additionalProperties);
        }
    }
}
