/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.transaction.types;

public interface ITransactionResponseCheckBase extends ITransactionResponseBase {
    int getCheckNumber();
}
