/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.entitygrouptypes.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.mercoa.api.core.ObjectMappers;
import java.io.IOException;
import java.util.Objects;

@JsonDeserialize(using = EntityIdOrBoolean.Deserializer.class)
public final class EntityIdOrBoolean {
    private final Object value;

    private final int type;

    private EntityIdOrBoolean(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((boolean) this.value);
        } else if (this.type == 1) {
            return visitor.visit((String) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EntityIdOrBoolean && equalTo((EntityIdOrBoolean) other);
    }

    private boolean equalTo(EntityIdOrBoolean other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static EntityIdOrBoolean of(boolean value) {
        return new EntityIdOrBoolean(value, 0);
    }

    public static EntityIdOrBoolean of(String value) {
        return new EntityIdOrBoolean(value, 1);
    }

    public interface Visitor<T> {
        T visit(boolean value);

        T visit(String value);
    }

    static final class Deserializer extends StdDeserializer<EntityIdOrBoolean> {
        Deserializer() {
            super(EntityIdOrBoolean.class);
        }

        @java.lang.Override
        public EntityIdOrBoolean deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            if (value instanceof Boolean) {
                return of((Boolean) value);
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, String.class));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
