/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.entitygrouptypes.types;

import java.util.List;
import java.util.Optional;

public interface IEntityGroupEntityUpdateRequest {
    Optional<List<String>> getEntityIds();
}
