/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.paymentgateway.validate;

import com.mercoa.api.core.ClientOptions;
import com.mercoa.api.core.RequestOptions;
import com.mercoa.api.resources.paymentgateway.validate.requests.SearchPaymentGatewayValidationJobsRequest;
import com.mercoa.api.resources.paymentgatewaytypes.types.SearchPaymentGatewayValidationJobsResponse;
import com.mercoa.api.resources.paymentgatewaytypes.types.ValidatePaymentGatewayRequest;
import com.mercoa.api.resources.paymentgatewaytypes.types.ValidatePaymentGatewayResponse;

public class ValidateClient {
    protected final ClientOptions clientOptions;

    private final RawValidateClient rawClient;

    public ValidateClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawValidateClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawValidateClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Search payment gateway validation jobs
     */
    public SearchPaymentGatewayValidationJobsResponse find() {
        return this.rawClient.find().body();
    }

    /**
     * Search payment gateway validation jobs
     */
    public SearchPaymentGatewayValidationJobsResponse find(SearchPaymentGatewayValidationJobsRequest request) {
        return this.rawClient.find(request).body();
    }

    /**
     * Search payment gateway validation jobs
     */
    public SearchPaymentGatewayValidationJobsResponse find(
            SearchPaymentGatewayValidationJobsRequest request, RequestOptions requestOptions) {
        return this.rawClient.find(request, requestOptions).body();
    }

    /**
     * Create a job to validate a payment gateway
     */
    public ValidatePaymentGatewayResponse create(ValidatePaymentGatewayRequest request) {
        return this.rawClient.create(request).body();
    }

    /**
     * Create a job to validate a payment gateway
     */
    public ValidatePaymentGatewayResponse create(ValidatePaymentGatewayRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    /**
     * Get the status of a payment gateway validation job
     */
    public ValidatePaymentGatewayResponse get(String jobId) {
        return this.rawClient.get(jobId).body();
    }

    /**
     * Get the status of a payment gateway validation job
     */
    public ValidatePaymentGatewayResponse get(String jobId, RequestOptions requestOptions) {
        return this.rawClient.get(jobId, requestOptions).body();
    }
}
