/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.organization.notificationconfiguration;

import com.mercoa.api.core.ClientOptions;
import com.mercoa.api.core.RequestOptions;
import com.mercoa.api.resources.entitytypes.types.NotificationType;
import com.mercoa.api.resources.organizationtypes.types.NotificationConfigurationRequest;
import com.mercoa.api.resources.organizationtypes.types.NotificationConfigurationResponse;
import java.util.List;

public class NotificationConfigurationClient {
    protected final ClientOptions clientOptions;

    private final RawNotificationConfigurationClient rawClient;

    public NotificationConfigurationClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawNotificationConfigurationClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawNotificationConfigurationClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve all notification configurations
     */
    public List<NotificationConfigurationResponse> getAll() {
        return this.rawClient.getAll().body();
    }

    /**
     * Retrieve all notification configurations
     */
    public List<NotificationConfigurationResponse> getAll(RequestOptions requestOptions) {
        return this.rawClient.getAll(requestOptions).body();
    }

    /**
     * Retrieve notification configuration for this notification type
     */
    public NotificationConfigurationResponse get(NotificationType notificationType) {
        return this.rawClient.get(notificationType).body();
    }

    /**
     * Retrieve notification configuration for this notification type
     */
    public NotificationConfigurationResponse get(NotificationType notificationType, RequestOptions requestOptions) {
        return this.rawClient.get(notificationType, requestOptions).body();
    }

    /**
     * Update notification configuration for this notification type
     */
    public NotificationConfigurationResponse update(
            NotificationType notificationType, NotificationConfigurationRequest request) {
        return this.rawClient.update(notificationType, request).body();
    }

    /**
     * Update notification configuration for this notification type
     */
    public NotificationConfigurationResponse update(
            NotificationType notificationType,
            NotificationConfigurationRequest request,
            RequestOptions requestOptions) {
        return this.rawClient.update(notificationType, request, requestOptions).body();
    }

    /**
     * Reset notification configuration for this notification type
     */
    public void reset(NotificationType notificationType) {
        this.rawClient.reset(notificationType).body();
    }

    /**
     * Reset notification configuration for this notification type
     */
    public void reset(NotificationType notificationType, RequestOptions requestOptions) {
        this.rawClient.reset(notificationType, requestOptions).body();
    }
}
