/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.banklookup.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mercoa.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BankAddress.Builder.class)
public final class BankAddress {
    private final String address;

    private final String city;

    private final String state;

    private final String postalCode;

    private final String postalCodeExtension;

    private final Map<String, Object> additionalProperties;

    private BankAddress(
            String address,
            String city,
            String state,
            String postalCode,
            String postalCodeExtension,
            Map<String, Object> additionalProperties) {
        this.address = address;
        this.city = city;
        this.state = state;
        this.postalCode = postalCode;
        this.postalCodeExtension = postalCodeExtension;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("address")
    public String getAddress() {
        return address;
    }

    @JsonProperty("city")
    public String getCity() {
        return city;
    }

    @JsonProperty("state")
    public String getState() {
        return state;
    }

    @JsonProperty("postalCode")
    public String getPostalCode() {
        return postalCode;
    }

    @JsonProperty("postalCodeExtension")
    public String getPostalCodeExtension() {
        return postalCodeExtension;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BankAddress && equalTo((BankAddress) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BankAddress other) {
        return address.equals(other.address)
                && city.equals(other.city)
                && state.equals(other.state)
                && postalCode.equals(other.postalCode)
                && postalCodeExtension.equals(other.postalCodeExtension);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.address, this.city, this.state, this.postalCode, this.postalCodeExtension);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AddressStage builder() {
        return new Builder();
    }

    public interface AddressStage {
        CityStage address(@NotNull String address);

        Builder from(BankAddress other);
    }

    public interface CityStage {
        StateStage city(@NotNull String city);
    }

    public interface StateStage {
        PostalCodeStage state(@NotNull String state);
    }

    public interface PostalCodeStage {
        PostalCodeExtensionStage postalCode(@NotNull String postalCode);
    }

    public interface PostalCodeExtensionStage {
        _FinalStage postalCodeExtension(@NotNull String postalCodeExtension);
    }

    public interface _FinalStage {
        BankAddress build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements AddressStage, CityStage, StateStage, PostalCodeStage, PostalCodeExtensionStage, _FinalStage {
        private String address;

        private String city;

        private String state;

        private String postalCode;

        private String postalCodeExtension;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(BankAddress other) {
            address(other.getAddress());
            city(other.getCity());
            state(other.getState());
            postalCode(other.getPostalCode());
            postalCodeExtension(other.getPostalCodeExtension());
            return this;
        }

        @java.lang.Override
        @JsonSetter("address")
        public CityStage address(@NotNull String address) {
            this.address = Objects.requireNonNull(address, "address must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("city")
        public StateStage city(@NotNull String city) {
            this.city = Objects.requireNonNull(city, "city must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("state")
        public PostalCodeStage state(@NotNull String state) {
            this.state = Objects.requireNonNull(state, "state must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("postalCode")
        public PostalCodeExtensionStage postalCode(@NotNull String postalCode) {
            this.postalCode = Objects.requireNonNull(postalCode, "postalCode must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("postalCodeExtension")
        public _FinalStage postalCodeExtension(@NotNull String postalCodeExtension) {
            this.postalCodeExtension =
                    Objects.requireNonNull(postalCodeExtension, "postalCodeExtension must not be null");
            return this;
        }

        @java.lang.Override
        public BankAddress build() {
            return new BankAddress(address, city, state, postalCode, postalCodeExtension, additionalProperties);
        }
    }
}
