/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.entitytypes.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mercoa.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = EntityHidePayorsRequest.Builder.class)
public final class EntityHidePayorsRequest {
    private final List<String> payors;

    private final Map<String, Object> additionalProperties;

    private EntityHidePayorsRequest(List<String> payors, Map<String, Object> additionalProperties) {
        this.payors = payors;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return List of payor entity IDs to hide
     */
    @JsonProperty("payors")
    public List<String> getPayors() {
        return payors;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EntityHidePayorsRequest && equalTo((EntityHidePayorsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EntityHidePayorsRequest other) {
        return payors.equals(other.payors);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.payors);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<String> payors = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(EntityHidePayorsRequest other) {
            payors(other.getPayors());
            return this;
        }

        @JsonSetter(value = "payors", nulls = Nulls.SKIP)
        public Builder payors(List<String> payors) {
            this.payors.clear();
            this.payors.addAll(payors);
            return this;
        }

        public Builder addPayors(String payors) {
            this.payors.add(payors);
            return this;
        }

        public Builder addAllPayors(List<String> payors) {
            this.payors.addAll(payors);
            return this;
        }

        public EntityHidePayorsRequest build() {
            return new EntityHidePayorsRequest(payors, additionalProperties);
        }
    }
}
