/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.entitytypes.types;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;

public interface IEntityResponse {
    String getId();

    String getName();

    String getEmail();

    Optional<String> getForeignId();

    Optional<String> getEmailTo();

    Optional<List<String>> getEmailToAlias();

    boolean getIsCustomer();

    AccountType getAccountType();

    ProfileResponse getProfile();

    Optional<String> getLogo();

    EntityStatus getStatus();

    Optional<String> getOatfiStatus();

    Optional<Map<String, String>> getOatfiUnderwritingResponse();

    boolean getAcceptedTos();

    boolean getIsPayor();

    boolean getIsPayee();

    boolean getIsNetworkPayor();

    boolean getIsNetworkPayee();

    Optional<Map<String, String>> getMetadata();

    OffsetDateTime getCreatedAt();

    OffsetDateTime getUpdatedAt();
}
