/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.entitytypes.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mercoa.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ProcessKybRequest.Builder.class)
public final class ProcessKybRequest {
    private final String reviewerEmail;

    private final List<MoovCapability> capabilities;

    private final Map<String, Object> additionalProperties;

    private ProcessKybRequest(
            String reviewerEmail, List<MoovCapability> capabilities, Map<String, Object> additionalProperties) {
        this.reviewerEmail = reviewerEmail;
        this.capabilities = capabilities;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("reviewerEmail")
    public String getReviewerEmail() {
        return reviewerEmail;
    }

    @JsonProperty("capabilities")
    public List<MoovCapability> getCapabilities() {
        return capabilities;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProcessKybRequest && equalTo((ProcessKybRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ProcessKybRequest other) {
        return reviewerEmail.equals(other.reviewerEmail) && capabilities.equals(other.capabilities);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.reviewerEmail, this.capabilities);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ReviewerEmailStage builder() {
        return new Builder();
    }

    public interface ReviewerEmailStage {
        _FinalStage reviewerEmail(@NotNull String reviewerEmail);

        Builder from(ProcessKybRequest other);
    }

    public interface _FinalStage {
        ProcessKybRequest build();

        _FinalStage capabilities(List<MoovCapability> capabilities);

        _FinalStage addCapabilities(MoovCapability capabilities);

        _FinalStage addAllCapabilities(List<MoovCapability> capabilities);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ReviewerEmailStage, _FinalStage {
        private String reviewerEmail;

        private List<MoovCapability> capabilities = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ProcessKybRequest other) {
            reviewerEmail(other.getReviewerEmail());
            capabilities(other.getCapabilities());
            return this;
        }

        @java.lang.Override
        @JsonSetter("reviewerEmail")
        public _FinalStage reviewerEmail(@NotNull String reviewerEmail) {
            this.reviewerEmail = Objects.requireNonNull(reviewerEmail, "reviewerEmail must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllCapabilities(List<MoovCapability> capabilities) {
            this.capabilities.addAll(capabilities);
            return this;
        }

        @java.lang.Override
        public _FinalStage addCapabilities(MoovCapability capabilities) {
            this.capabilities.add(capabilities);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "capabilities", nulls = Nulls.SKIP)
        public _FinalStage capabilities(List<MoovCapability> capabilities) {
            this.capabilities.clear();
            this.capabilities.addAll(capabilities);
            return this;
        }

        @java.lang.Override
        public ProcessKybRequest build() {
            return new ProcessKybRequest(reviewerEmail, capabilities, additionalProperties);
        }
    }
}
