/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mercoa.api.resources.entitytypes.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

public final class Trigger {
    private final Value value;

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    private Trigger(Value value) {
        this.value = value;
    }

    public <T> T visit(Visitor<T> visitor) {
        return value.visit(visitor);
    }

    public static Trigger amount(AmountTrigger value) {
        return new Trigger(new AmountValue(value));
    }

    public static Trigger all(Object value) {
        return new Trigger(new AllValue(value));
    }

    public boolean isAmount() {
        return value instanceof AmountValue;
    }

    public boolean isAll() {
        return value instanceof AllValue;
    }

    public boolean _isUnknown() {
        return value instanceof _UnknownValue;
    }

    public Optional<AmountTrigger> getAmount() {
        if (isAmount()) {
            return Optional.of(((AmountValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Object> getAll() {
        if (isAll()) {
            return Optional.of(((AllValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Object> _getUnknown() {
        if (_isUnknown()) {
            return Optional.of(((_UnknownValue) value).value);
        }
        return Optional.empty();
    }

    @JsonValue
    private Value getValue() {
        return this.value;
    }

    public interface Visitor<T> {
        T visitAmount(AmountTrigger amount);

        T visitAll(Object all);

        T _visitUnknown(Object unknownType);
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = true, defaultImpl = _UnknownValue.class)
    @JsonSubTypes({@JsonSubTypes.Type(AmountValue.class), @JsonSubTypes.Type(AllValue.class)})
    @JsonIgnoreProperties(ignoreUnknown = true)
    private interface Value {
        <T> T visit(Visitor<T> visitor);
    }

    @JsonTypeName("amount")
    private static final class AmountValue implements Value {
        @JsonUnwrapped
        private AmountTrigger value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private AmountValue() {}

        private AmountValue(AmountTrigger value) {
            this.value = value;
        }

        @Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitAmount(value);
        }

        @Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof AmountValue && equalTo((AmountValue) other);
        }

        private boolean equalTo(AmountValue other) {
            return value.equals(other.value);
        }

        @Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @Override
        public String toString() {
            return "Trigger{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("all")
    private static final class AllValue implements Value {
        @JsonProperty("value")
        private Object value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private AllValue(@JsonProperty("value") Object value) {
            this.value = value;
        }

        @Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitAll(value);
        }

        @Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof AllValue && equalTo((AllValue) other);
        }

        private boolean equalTo(AllValue other) {
            return value.equals(other.value);
        }

        @Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @Override
        public String toString() {
            return "Trigger{" + "value: " + value + "}";
        }
    }

    private static final class _UnknownValue implements Value {
        private String type;

        @JsonValue
        private Object value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private _UnknownValue(@JsonProperty("value") Object value) {}

        @Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor._visitUnknown(value);
        }

        @Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof _UnknownValue && equalTo((_UnknownValue) other);
        }

        private boolean equalTo(_UnknownValue other) {
            return type.equals(other.type) && value.equals(other.value);
        }

        @Override
        public int hashCode() {
            return Objects.hash(this.type, this.value);
        }

        @Override
        public String toString() {
            return "Trigger{" + "type: " + type + ", value: " + value + "}";
        }
    }
}
